  CREATE UNIQUE INDEX "ERP_CARGO_FUNCIONARIO_PK" ON "ERP_CARGO_FUNCIONARIO" ("ID") 
  ;

  CREATE UNIQUE INDEX "ERP_CLIENTE_CPF_UK" ON "ERP_CLIENTE" ("CPF") 
  ;

  CREATE UNIQUE INDEX "ERP_CLIENTE_ENDERECO_PK" ON "ERP_CLIENTE_ENDERECO" ("ID", "ERP_CLIENTE_ID") 
  ;

  CREATE UNIQUE INDEX "ERP_CLIENTE_PK" ON "ERP_CLIENTE" ("ID") 
  ;

  CREATE UNIQUE INDEX "ERP_COMPRA_ITEM_PK" ON "ERP_COMPRA_ITEM" ("ID") 
  ;

  CREATE UNIQUE INDEX "ERP_COMPRA_PK" ON "ERP_COMPRA" ("ID") 
  ;

  CREATE UNIQUE INDEX "ERP_CONTATO_CLIENTE_PK" ON "ERP_CONTATO_CLIENTE" ("ID") 
  ;

  CREATE UNIQUE INDEX "ERP_ESTADO_PK" ON "ERP_ESTADO" ("ID") 
  ;

  CREATE UNIQUE INDEX "ERP_FILIAL_PK" ON "ERP_FILIAL" ("ID") 
  ;

  CREATE UNIQUE INDEX "ERP_FORNECEDOR_PK" ON "ERP_FORNECEDOR" ("ID") 
  ;

  CREATE UNIQUE INDEX "ERP_FUNCIONARIO_PK" ON "ERP_FUNCIONARIO" ("ID") 
  ;

  CREATE UNIQUE INDEX "ERP_ORCAMENTO_COMPRA_PK" ON "ERP_ORCAMENTO_COMPRA" ("ID") 
  ;

  CREATE UNIQUE INDEX "ERP_USUARIO_EMAIL_UK" ON "ERP_USUARIO" ("EMAIL") 
  ;

  CREATE UNIQUE INDEX "ERP_USUARIO_LOGIN_UK" ON "ERP_USUARIO" ("LOGIN") 
  ;

  CREATE UNIQUE INDEX "ERP_USUARIO_PK" ON "ERP_USUARIO" ("ID") 
  ;

  CREATE UNIQUE INDEX "ERP_VENDA_ITEM_PK" ON "ERP_VENDA_ITEM" ("ID") 
  ;

  CREATE UNIQUE INDEX "ERP_VENDA_PK" ON "ERP_VENDA" ("ID") 
  ;

  CREATE UNIQUE INDEX "PRODUTO_PK" ON "ERP_PRODUTO" ("ID") 
  ;

  CREATE UNIQUE INDEX "TIPO_CONTATO_PK" ON "ERP_TIPO_CONTATO" ("ID") 
  ; 